CREATE TABLE [dbo].[Guest]
(
	[Id] UNIQUEIDENTIFIER NOT NULL
		CONSTRAINT DF_Guest_Id DEFAULT (NEWSEQUENTIALID()),
	[LastName] NVARCHAR(75) NOT NULL,
	[FirstName] NVARCHAR(75) NOT NULL,
	[ReservationId] NCHAR(12) NOT NULL,
    CONSTRAINT [PK_Guest] PRIMARY KEY ([Id]) 
)
